/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package videoindexersamples;

import videoindexersamples.Account.Account;
import videoindexersamples.authentication.ArmAccessTokenPermission;
import videoindexersamples.authentication.ArmAccessTokenScope;

public class App {

    private static final String VideoUrl = "";

    public static void main(String[] args) {

        System.out.println("Video Indexer API Samples");
        System.out.println("==========================");

        System.out.println("Creating Video Indexer Client Instance");
        var videoIndexerClient = VideoIndexerClient.build();

        // You can use the account Access Token for subsequent requests , in this demo it is stored inside the VideoIndexer Client.
        // The Token is valid for 1 hour
        System.out.println("Get Account Access Token");
        if (!videoIndexerClient.getAccountAccessToken(ArmAccessTokenPermission.Contributor, ArmAccessTokenScope.Account, null, null)) {
            System.out.println("Could not retreive Account Access Token. check result code");
            return;
        }

        //Get Account Information
        Account account = videoIndexerClient.getAccount();
        System.out.printf("The account ID is %s\n", account.properties.accountId);
        System.out.printf("The account Location is %s\n", account.location);

        //Upload Video + Polling for Completion Event
        var videoId = videoIndexerClient.uploadVideo(VideoUrl,"video345");
        System.out.printf("Successfully uploaded video with Id: %s\n",videoId);
        var waitResult = videoIndexerClient.waitForIndex(videoId);
        System.out.println("wait result  = " + waitResult);

        //Get Index Insights
        var videoMetadata = videoIndexerClient.getVideo(videoId);
        System.out.printf("Video Metadata : \n%s\n",videoMetadata);
    }

}
