/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package videoindexersamples;

import videoindexersamples.Account.Account;
import videoindexersamples.authentication.ArmAccessTokenPermission;
import videoindexersamples.authentication.ArmAccessTokenScope;

public class App {

    private static final String VideoUrl = "https://vimaptestfilessa.blob.core.windows.net/benchmark-tests/all-complex-long.mp4?sv=2021-10-04&st=2023-02-12T11%3A06%3A14Z&se=2023-04-13T10%3A06%3A00Z&sr=b&sp=r&sig=DBVuvHTc37cM3nApRGsuiP0dbhSARpRIsr55U%2FWL7Qk%3D";

    public static void main(String[] args) {

        System.out.println("Video Indexer API Samples");
        System.out.println("==========================");

        System.out.println("Creating Video Indexer Client Instance");
        var videoIndexerClient = VideoIndexerClient.build();

        // You can use the account Access Token for subsequent requests , in this demo it is stored inside the VideoIndexer Client.
        // The Token is valid for 1 hour
        System.out.println("Get Account Access Token");
        videoIndexerClient.getAccountAccessToken(ArmAccessTokenPermission.Contributor, ArmAccessTokenScope.Account, null, null);


        //Get Account Information
        Account account = videoIndexerClient.getAccount();
        System.out.printf("The account ID is %s\n", account.properties.accountId);
        System.out.printf("The account Location is %s\n", account.location);

        //Upload Video
        var response = videoIndexerClient.uploadVideo(VideoUrl);
        System.out.println(response);


    }

}
