using System;
using System.Collections.Generic;

namespace EnrichmentPipeline.Functions.Domain.Models
{
    /// <summary>
    /// A model for storing and transporting key data about a blob in storage.
    /// </summary>
    public class BlobInfo
    {
        /// <summary>
        /// The unique correlation token for the blob as it passes through the system. This can be used to query reports and logs.
        /// </summary>
        public Guid CorrelationId { get; set; } = Guid.NewGuid();

        /// <summary>
        /// The absolute, canonical Uri for the blob in storage.
        /// </summary>
        public Uri CanonicalUri { get; set; }

        /// <summary>
        /// The absolute uri for the blob with a SAS token.
        /// </summary>
        public Uri SasUri { get; set; }

        /// <summary>
        /// The date/time that the sas token expires.
        /// </summary>
        public DateTime SasExpiry { get; set; }

        /// <summary>
        /// The file name of the blob, for example 'Video.mp4'.
        /// </summary>
        public string FileName { get; set; }

        /// <summary>
        /// The file category for the blob. digitaltext, image or video are the expected values.
        /// </summary>
        public string FileCategory { get; set; }

        /// <summary>
        /// The system version.
        /// </summary>
        public string SystemVersion { get; set; }

        /// <summary>
        /// A collection of key-values pairs. An extensibility point for passing additional data with the blobinfo. 
        /// </summary>
        public IDictionary<string, string> MetaData { get; set; }

        /// <summary>
        /// The MD5 hash for the blob in hex format as generated by Azure storage.
        /// </summary>
        public string Hash { get; set; }
    }
}
