# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  displayName: 'Validate Logic App JSON'
  inputs:
    targetType: 'inline'
    script: |
      foreach ($workflow in Get-ChildItem ./logicapp -Directory) {
          Get-Content -raw "$workflow/armtemplate.json" | Test-json
      }
    failOnStderr: true
    showWarnings: true

- task: UseDotNet@2
  displayName: 'Use Dotnet 3.0.x'
  inputs:
    version: '3.0.x'
    packageType: runtime
 
- task: DotNetCoreCLI@2
  displayName: "Install Dotnet Format"
  inputs:
    command: custom
    custom: tool
    arguments: install -g dotnet-format

- script: 'dotnet format --check --verbosity diagnostic'
  displayName: 'Run Dotnet Format'
  workingDirectory: 'functions/'

- task: DotNetCoreCLI@2  
  displayName: 'Run Dotnet Restore'  
  inputs:  
    command: restore  
    projects: 'functions/**/*.csproj'  
    includeNuGetOrg: true 

- task: DotNetCoreCLI@2
  displayName: 'Run Dotnet Build'
  inputs:
    command: 'build'
    projects: 'functions/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Dotnet Test'
  inputs:
    command: 'test'
    projects: 'functions/**/*Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "XPlat Code coverage" -- RunConfiguration.DisableAppDomain=true'
    publishTestResults: true 

- task: TerraformCLI@0
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/'
    commandOptions: '-backend=false'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: 'Terraform Validate'
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/'
    allowTelemetryCollection: true
